# Generated by Django 5.1.4 on 2025-01-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='study_branch',
            field=models.CharField(choices=[('E', 'Elektrotechnika'), ('IT', 'Informační technologie')], default='E', help_text='Obor studia (E = Elektrotechnika, IT = Informační technologie).', max_length=2),
        ),
    ]
