# Generated by Django 5.1.4 on 2025-01-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_study_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, help_text='Titul (např. Mgr., Ing., Ph.D. apod.)', max_length=50, verbose_name='Titul'),
        ),
    ]
