# Generated by Django 5.1.4 on 2025-01-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='study_branch',
            field=models.CharField(choices=[('-', 'Učitel'), ('E', 'Elektrotechnika'), ('IT', 'Informační technologie')], default='-', help_text='Obor studia (E = Elektrotechnika, IT = Informační technologie).', max_length=2),
        ),
    ]
