# Generated by Django 5.1.4 on 2025-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_school_year_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school_year',
            field=models.CharField(default='2024/2025', help_text='Školní rok studenta (např. 2024/2025, 2025/2026)', max_length=20, verbose_name='Školní rok'),
        ),
    ]
