# Generated by Django 5.1.4 on 2025-03-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Zkratka příjmení', max_length=10, verbose_name='Zkratka příjmení'),
        ),
    ]
