# Generated by Django 5.1.4 on 2025-01-10 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Krátký popis milníku', max_length=200)),
                ('deadline', models.DateField(blank=True, help_text='Datum, do kdy je milník plánován', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Nezahájeno'), ('in_progress', 'Rozpracováno'), ('done', 'Dokončeno')], default='not_started', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Poznámka k milníku')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
        ),
    ]
