# Generated by Django 5.1.4 on 2025-01-13 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_scoringscheme_project_internal_notes_controlcheck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assignment',
            field=models.TextField(blank=True, help_text='Oficiální zadání (needitovatelné studentem)'),
        ),
        migrations.AlterField(
            model_name='controlcheck',
            name='content',
            field=models.TextField(help_text='Co bylo náplní kontroly', verbose_name='Obsah'),
        ),
        migrations.AlterField(
            model_name='controlcheck',
            name='date',
            field=models.DateField(help_text='Datum kontroly', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='controlcheck',
            name='evaluation',
            field=models.CharField(blank=True, help_text='Hodnocení / body / slovní', max_length=200, verbose_name='Hodnocení'),
        ),
        migrations.AlterField(
            model_name='controlcheck',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='leaderevaluation',
            name='area1_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='leaderevaluation',
            name='area1_text',
            field=models.TextField(blank=True, help_text='Popis hodnocení (oblast 1)', verbose_name='Oblast 1'),
        ),
        migrations.AlterField(
            model_name='leaderevaluation',
            name='area2_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='leaderevaluation',
            name='area2_text',
            field=models.TextField(blank=True, help_text='Popis hodnocení (oblast 2)', verbose_name='Oblast 2'),
        ),
        migrations.AlterField(
            model_name='leaderevaluation',
            name='area3_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='leaderevaluation',
            name='area3_text',
            field=models.TextField(blank=True, help_text='Popis hodnocení (oblast 3)', verbose_name='Oblast 3'),
        ),
        migrations.AlterField(
            model_name='leaderevaluation',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_eval', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='deadline',
            field=models.DateField(blank=True, help_text='Datum, do kdy je milník plánován', null=True, verbose_name='Termín'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='note',
            field=models.TextField(blank=True, help_text='Poznámka k milníku', verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('not_started', 'Nezahájeno'), ('in_progress', 'Rozpracováno'), ('done', 'Dokončeno')], default='not_started', max_length=20, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(help_text='Krátký popis milníku', max_length=200, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='opponentevaluation',
            name='area1_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='opponentevaluation',
            name='area1_text',
            field=models.TextField(blank=True, help_text='Popis hodnocení (oblast 1)', verbose_name='Oblast 1'),
        ),
        migrations.AlterField(
            model_name='opponentevaluation',
            name='area2_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='opponentevaluation',
            name='area2_text',
            field=models.TextField(blank=True, help_text='Popis hodnocení (oblast 2)', verbose_name='Oblast 2'),
        ),
        migrations.AlterField(
            model_name='opponentevaluation',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_eval', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='project',
            name='edit_deadline',
            field=models.DateTimeField(blank=True, help_text='Do kdy může student upravovat projekt', null=True, verbose_name='Upravit do'),
        ),
        migrations.AlterField(
            model_name='project',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Poznámky viditelné pouze pro vedoucího (WYSIWYG)', verbose_name='Interní poznámky'),
        ),
        migrations.AlterField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Vedoucí projektu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='opponent',
            field=models.ForeignKey(blank=True, help_text='Oponent projektu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='Scoring schema pro tento projekt (podle školního roku)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.scoringscheme', verbose_name='Scoring schema'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Čeká na schválení'), ('approved', 'Schváleno'), ('finished', 'Dokončeno')], default='pending_approval', max_length=20, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='scoringscheme',
            name='leader_area1_max',
            field=models.PositiveIntegerField(default=15, help_text='Maximální počet bodů za oblast 1', verbose_name='Max. body oblast 1'),
        ),
        migrations.AlterField(
            model_name='scoringscheme',
            name='leader_area2_max',
            field=models.PositiveIntegerField(default=10, help_text='Maximální počet bodů za oblast 2', verbose_name='Max. body oblast 2'),
        ),
        migrations.AlterField(
            model_name='scoringscheme',
            name='leader_area3_max',
            field=models.PositiveIntegerField(default=15, help_text='Maximální počet bodů za oblast 3', verbose_name='Max. body oblast 3'),
        ),
        migrations.AlterField(
            model_name='scoringscheme',
            name='opponent_area1_max',
            field=models.PositiveIntegerField(default=15, help_text='Maximální počet bodů za oblast 1', verbose_name='Max. body oblast 1'),
        ),
        migrations.AlterField(
            model_name='scoringscheme',
            name='opponent_area2_max',
            field=models.PositiveIntegerField(default=15, help_text='Maximální počet bodů za oblast 2', verbose_name='Max. body oblast 2'),
        ),
        migrations.AlterField(
            model_name='scoringscheme',
            name='year',
            field=models.CharField(help_text='Školní rok, např. 2024/2025', max_length=20, unique=True, verbose_name='Školní rok'),
        ),
    ]
