# Generated by Django 5.1.4 on 2025-01-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_assignment_alter_controlcheck_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringscheme',
            name='edit_deadline',
            field=models.DateTimeField(blank=True, help_text='Do kdy smí student editovat projekt', null=True),
        ),
    ]
