# Generated by Django 5.1.4 on 2025-01-13 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_scoringscheme_edit_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_myprojects_default', models.BooleanField(default=False, help_text='Zobrazovat rovnou moje projekty')),
                ('email_notifications', models.BooleanField(default=True, help_text='Zasílat e-mail notifikace')),
                ('consultation_text1', models.TextField(blank=True, help_text='Předdefinovaný text konzultace #1')),
                ('consultation_text2', models.TextField(blank=True, help_text='Předdefinovaný text konzultace #2')),
                ('consultation_text3', models.TextField(blank=True, help_text='Předdefinovaný text konzultace #3')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
