# Generated by Django 5.1.4 on 2025-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringscheme',
            name='control_deadline1',
            field=models.DateField(blank=True, help_text='Termín kontroly #1', null=True, verbose_name='Kontrola #1'),
        ),
        migrations.AddField(
            model_name='scoringscheme',
            name='control_deadline2',
            field=models.DateField(blank=True, help_text='Termín kontroly #2', null=True, verbose_name='Kontrola #2'),
        ),
        migrations.AddField(
            model_name='scoringscheme',
            name='control_deadline3',
            field=models.DateField(blank=True, help_text='Termín kontroly #3', null=True, verbose_name='Kontrola #3'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='consultation_text1',
            field=models.TextField(blank=True, help_text='Předdefinovaný text konzultace #1', verbose_name='Konzultace #1'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='consultation_text2',
            field=models.TextField(blank=True, help_text='Předdefinovaný text konzultace #2', verbose_name='Konzultace #2'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='consultation_text3',
            field=models.TextField(blank=True, help_text='Předdefinovaný text konzultace #3', verbose_name='Konzultace #3'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Zasílat e-mail notifikace', verbose_name='E-mail notifikace'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='pref_myprojects_default',
            field=models.BooleanField(default=False, help_text='Zobrazovat rovnou moje projekty', verbose_name='Moje projekty'),
        ),
    ]
