# Generated by Django 5.1.4 on 2025-01-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_scoringscheme_control_deadline1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringscheme',
            old_name='edit_deadline',
            new_name='student_edit_deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='edit_deadline',
        ),
        migrations.AlterField(
            model_name='project',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='Scoring schema pro tento projekt (podle školního roku)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.scoringscheme', verbose_name='Scoring schema'),
        ),
    ]
