# Generated by Django 5.1.4 on 2025-01-27 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_edit_deadline_scoringscheme_student_edit_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderevaluation',
            name='export_date',
            field=models.DateField(blank=True, help_text='Datum exportu hodnocení', null=True, verbose_name='Datum exportu'),
        ),
        migrations.AddField(
            model_name='leaderevaluation',
            name='submission_status',
            field=models.CharField(blank=True, choices=[('on_time', 'Odevzdal v řádném termínu'), ('late', 'Odevzdal v náhradním termínu'), ('not_submitted', 'Neodevzdal v termínu')], help_text='Stav odevzdání hodnocení', max_length=50, null=True, verbose_name='Stav odevzdání'),
        ),
        migrations.AddField(
            model_name='opponentevaluation',
            name='export_date',
            field=models.DateField(blank=True, help_text='Datum exportu hodnocení', null=True, verbose_name='Datum exportu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assignment',
            field=models.TextField(blank=True, help_text='Oficiální zadání (needitovatelné studentem)', verbose_name='Zadání'),
        ),
        migrations.AlterField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Vedoucí projektu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_projects', to=settings.AUTH_USER_MODEL, verbose_name='Vedoucí'),
        ),
        migrations.AlterField(
            model_name='project',
            name='opponent',
            field=models.ForeignKey(blank=True, help_text='Oponent projektu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_projects', to=settings.AUTH_USER_MODEL, verbose_name='Oponent'),
        ),
    ]
