# Generated by Django 5.1.4 on 2025-01-27 21:36

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_leaderevaluation_export_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='signature',
            field=models.ImageField(blank=True, help_text='Nahrajte podpis (JPEG/PNG, max. 1 MB, max. 700x300 px).', null=True, upload_to='signatures/', validators=[apps.projects.models.validate_image]),
        ),
    ]
