# Generated by Django 5.1.4 on 2025-01-31 14:51

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_userpreferences_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Poznámky viditelné pouze pro vedoucího práce', verbose_name='Interní poznámky'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='signature',
            field=models.ImageField(blank=True, help_text='Nahrajte podpis (JPEG/PNG, max. 1 MB, max. 800x400 px).', null=True, upload_to='signatures/', validators=[apps.projects.models.validate_image], verbose_name='Podpis'),
        ),
    ]
