# Generated by Django 5.1.4 on 2025-02-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_internal_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_documentation_date',
            field=models.DateField(blank=True, help_text='Datum předání dokumentace', null=True, verbose_name='Datum předání dokumentace'),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_work_date',
            field=models.DateField(blank=True, help_text='Datum předání výrobku', null=True, verbose_name='Datum předání výrobku'),
        ),
    ]
