# Generated by Django 5.1.4 on 2025-02-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_delivery_documentation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderevaluation',
            name='area1_text',
            field=models.TextField(blank=True, help_text='Úplnost, funkčnost, zpracování, obtížnost, invence', verbose_name='Kvalita výrobku (počet bodů 0 - 14)'),
        ),
        migrations.AlterField(
            model_name='leaderevaluation',
            name='area2_text',
            field=models.TextField(blank=True, help_text='Odborný obsah, formální stránka', verbose_name='Dokumentace (počet bodů 0 - 8)'),
        ),
        migrations.AlterField(
            model_name='leaderevaluation',
            name='area3_text',
            field=models.TextField(blank=True, help_text='Dodržování termínů konzultací, průběžné plnění zadaných úkolů, samostatnost, orientace v problematice', verbose_name='Průběžné kontroly plnění zadaných úkolů (počet bodů 0 - 18)'),
        ),
        migrations.AlterField(
            model_name='opponentevaluation',
            name='area1_text',
            field=models.TextField(blank=True, help_text='Úplnost, funkčnost, zpracování, obtížnost, invence', verbose_name='Oblast výrobku (počet bodů 0 - 12)'),
        ),
        migrations.AlterField(
            model_name='opponentevaluation',
            name='area2_text',
            field=models.TextField(blank=True, help_text='Odborný obsah, přehledná a srozumitelná prezentace výsledků', verbose_name='Dokumentace (počet bodů 0 - 12)'),
        ),
    ]
