# Generated by Django 5.1.4 on 2025-02-07 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_leaderevaluation_area1_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assignment',
            field=models.TextField(blank=True, help_text='Oficiální zadání (needitovatelné žákem)', verbose_name='Zadání'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Žák', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
