# Generated by Django 5.1.4 on 2025-02-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_assignment_alter_project_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='default_year',
            field=models.CharField(default='2024/2025', help_text="Výchozí školní rok, se kterým chcete pracovat (např. '2024/2025').", max_length=20, verbose_name='Výchozí školní rok'),
        ),
    ]
