# Generated by Django 5.1.4 on 2025-02-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_userpreferences_default_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_leader',
            field=models.CharField(blank=True, help_text='Jméno externího vedoucího projektu (neregistrovaný uživatel)', max_length=200, verbose_name='Externí vedoucí'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_leader_email',
            field=models.EmailField(blank=True, help_text='E-mail externího vedoucího', max_length=254, verbose_name='E-mail externího vedoucího'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_leader_phone',
            field=models.CharField(blank=True, help_text='Telefon externího vedoucího', max_length=20, verbose_name='Telefon externího vedoucího'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_opponent',
            field=models.CharField(blank=True, help_text='Jméno externího oponenta projektu (neregistrovaný uživatel)', max_length=200, verbose_name='Externí oponent'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_opponent_email',
            field=models.EmailField(blank=True, help_text='E-mail externího oponenta', max_length=254, verbose_name='E-mail externího oponenta'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_opponent_phone',
            field=models.CharField(blank=True, help_text='Telefon externího oponenta', max_length=20, verbose_name='Telefon externího oponenta'),
        ),
    ]
