# Generated by Django 5.1.4 on 2025-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_external_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Čeká na schválení'), ('approved', 'Schváleno'), ('finished', 'Dokončeno'), ('rejected', 'Zamítnuto'), ('cancelled', 'Zrušeno')], default='pending_approval', max_length=20, verbose_name='Stav'),
        ),
    ]
