# Generated by Django 5.1.4 on 2025-02-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_leaderevaluation_defense_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderevaluation',
            name='questions_visible',
            field=models.BooleanField(default=False, help_text='Zveřejnit otázky žákovi', verbose_name='Zveřejnit otázky'),
        ),
        migrations.AlterField(
            model_name='opponentevaluation',
            name='questions_visible',
            field=models.BooleanField(default=False, help_text='Zveřejnit otázky žákovi', verbose_name='Zveřejnit otázky'),
        ),
    ]
