# Generated by Django 5.1.4 on 2025-02-28 11:40

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_leaderevaluation_questions_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='portfolio_url1',
            field=models.URLField(blank=True, help_text='URL adresa portfolia nebo projektu (např. GitHub, Behance)', validators=[apps.projects.models.validate_safe_url], verbose_name='Portfolio URL 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio_url2',
            field=models.URLField(blank=True, help_text='Další URL adresa portfolia nebo projektu', validators=[apps.projects.models.validate_safe_url], verbose_name='Portfolio URL 2'),
        ),
    ]
