# Generated by Django 5.1.4 on 2025-03-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_portfolio_url1_project_portfolio_url2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assignment',
            field=models.TextField(blank=True, help_text='Oficiální zadání (needitovatelné žákem)', verbose_name='Oficiální zadání'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Žákův popis projektu, čeho chce dosáhnout', verbose_name='Žákova vize'),
        ),
    ]
