# Generated by Django 5.1.4 on 2025-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_assignment_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringscheme',
            name='delivery_documentation_deadline',
            field=models.DateField(blank=True, help_text='Termín předání dokumentace', null=True, verbose_name='Termín předání dokumentace'),
        ),
        migrations.AddField(
            model_name='scoringscheme',
            name='delivery_work_deadline',
            field=models.DateField(blank=True, help_text='Termín předání výrobku', null=True, verbose_name='Termín předání výrobku'),
        ),
    ]
