# Generated by Django 5.1.4 on 2025-03-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_scoringscheme_delivery_documentation_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delayed_submission_date',
            field=models.DateField(blank=True, help_text='Datum odkladu odevzdání práce', null=True, verbose_name='Datum odkladu'),
        ),
    ]
