# Generated by Django 5.1.4 on 2025-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_delayed_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='delayed_submission_date',
            field=models.DateField(blank=True, help_text='Datum odkladu odevzdání práce', null=True, verbose_name='Datum odkladu odevzdání práce'),
        ),
    ]
